-- NebulaDesk control plane schema.
--
-- Design notes that are not obvious from the DDL alone:
--
-- * Every tenant-scoped table carries `tenant_id` even where it could be
--   derived by joining. Multi-tenancy bugs are catastrophic and silent, so
--   every query filters on it directly and composite foreign keys make a
--   cross-tenant reference impossible to insert.
-- * Identifiers are UUIDv7, generated by the application. They sort by
--   creation time, so primary key inserts stay at the right edge of the
--   B-tree instead of scattering writes like UUIDv4.
-- * Secrets are stored hashed, never encrypted: nothing here ever needs to be
--   read back, only compared.

CREATE TABLE tenants (
    id          UUID PRIMARY KEY,
    name        TEXT        NOT NULL,
    slug        TEXT        NOT NULL UNIQUE,
    disabled    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    tenant_id     UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    display_name  TEXT        NOT NULL,
    role          TEXT        NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'USER')),
    disabled      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Two tenants may each have an alice@example.com; they are different people.
    UNIQUE (tenant_id, email),
    -- Lets child tables key on (tenant_id, user_id) so a membership can never
    -- straddle two tenants.
    UNIQUE (tenant_id, id)
);

CREATE TABLE user_groups (
    id         UUID PRIMARY KEY,
    tenant_id  UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id)
);

CREATE TABLE user_group_members (
    tenant_id UUID NOT NULL,
    group_id  UUID NOT NULL,
    user_id   UUID NOT NULL,
    PRIMARY KEY (group_id, user_id),
    FOREIGN KEY (tenant_id, group_id) REFERENCES user_groups (tenant_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX user_group_members_user_idx ON user_group_members (tenant_id, user_id);

-- Edge nodes. Registered by an operator, not self-service.
CREATE TABLE gateways (
    id            UUID PRIMARY KEY,
    name          TEXT        NOT NULL UNIQUE,
    public_url    TEXT        NOT NULL,
    quic_addr     TEXT        NOT NULL,
    cert_pin      TEXT        NOT NULL,
    region        TEXT        NOT NULL DEFAULT 'default',
    capacity      INTEGER     NOT NULL DEFAULT 1000,
    load          INTEGER     NOT NULL DEFAULT 0,
    secret_hash   TEXT        NOT NULL,
    last_seen_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE relays (
    id            UUID PRIMARY KEY,
    name          TEXT        NOT NULL UNIQUE,
    quic_addr     TEXT        NOT NULL,
    cert_pin      TEXT        NOT NULL,
    region        TEXT        NOT NULL DEFAULT 'default',
    capacity_mbps INTEGER     NOT NULL DEFAULT 1000,
    load          INTEGER     NOT NULL DEFAULT 0,
    secret_hash   TEXT        NOT NULL,
    last_seen_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One enrolled server machine running nebula-agent.
CREATE TABLE machines (
    id                UUID PRIMARY KEY,
    tenant_id         UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name              TEXT        NOT NULL,
    os                TEXT        NOT NULL CHECK (os IN ('WINDOWS', 'MACOS', 'LINUX')),
    os_version        TEXT        NOT NULL DEFAULT '',
    arch              TEXT        NOT NULL DEFAULT '',
    agent_version     TEXT        NOT NULL DEFAULT '',
    -- The agent's Noise static public key. This is the root of the
    -- end-to-end guarantee: a client encrypts to this key, so no relay or
    -- gateway can impersonate the machine.
    noise_public_key  BYTEA       NOT NULL,
    credential_hash   TEXT        NOT NULL,
    owner_user_id     UUID,
    status            TEXT        NOT NULL DEFAULT 'OFFLINE'
                          CHECK (status IN ('OFFLINE', 'ONLINE', 'DRAINING')),
    gateway_id        UUID REFERENCES gateways (id) ON DELETE SET NULL,
    capabilities      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    last_seen_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, id),
    -- A machine's Noise key must be globally unique: two machines sharing one
    -- would let either answer for the other.
    UNIQUE (noise_public_key),
    FOREIGN KEY (tenant_id, owner_user_id) REFERENCES users (tenant_id, id) ON DELETE SET NULL
);

CREATE INDEX machines_tenant_status_idx ON machines (tenant_id, status);

-- Single-use tokens that let an agent enrol itself unattended.
CREATE TABLE enrollment_tokens (
    id            UUID PRIMARY KEY,
    tenant_id     UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    token_hash    TEXT        NOT NULL UNIQUE,
    -- Pins the machine name so a leaked token cannot enrol an impostor under
    -- an arbitrary identity.
    machine_name  TEXT,
    owner_user_id UUID,
    expires_at    TIMESTAMPTZ NOT NULL,
    used_at       TIMESTAMPTZ,
    used_by       UUID REFERENCES machines (id) ON DELETE SET NULL,
    created_by    UUID,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, owner_user_id) REFERENCES users (tenant_id, id) ON DELETE SET NULL
);

-- What a machine offers: its whole desktop, or one specific application.
CREATE TABLE published_resources (
    id           UUID PRIMARY KEY,
    tenant_id    UUID        NOT NULL,
    machine_id   UUID        NOT NULL,
    kind         TEXT        NOT NULL CHECK (kind IN ('DESKTOP', 'APP')),
    name         TEXT        NOT NULL,
    description  TEXT        NOT NULL DEFAULT '',
    icon         BYTEA,
    launch_path  TEXT,
    launch_args  TEXT[]      NOT NULL DEFAULT '{}',
    working_dir  TEXT,
    -- How the agent recognises this application's windows when capturing.
    window_match JSONB       NOT NULL DEFAULT '{}'::jsonb,
    enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (machine_id, name),
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, id) ON DELETE CASCADE,
    -- An APP without something to launch is unusable; a DESKTOP with one is
    -- a configuration mistake that would silently do nothing.
    CONSTRAINT app_needs_launch_path CHECK (
        (kind = 'APP' AND launch_path IS NOT NULL)
        OR (kind = 'DESKTOP' AND launch_path IS NULL)
    )
);

CREATE INDEX published_resources_machine_idx ON published_resources (tenant_id, machine_id);

-- Who may use a resource, and how.
CREATE TABLE entitlements (
    id                 UUID PRIMARY KEY,
    tenant_id          UUID        NOT NULL,
    resource_id        UUID        NOT NULL,
    subject_kind       TEXT        NOT NULL CHECK (subject_kind IN ('USER', 'GROUP')),
    subject_id         UUID        NOT NULL,
    role               TEXT        NOT NULL CHECK (role IN ('VIEWER', 'CONTROLLER', 'ADMIN')),
    allow_clipboard    BOOLEAN     NOT NULL DEFAULT FALSE,
    allow_file_transfer BOOLEAN    NOT NULL DEFAULT FALSE,
    allow_audio        BOOLEAN     NOT NULL DEFAULT TRUE,
    expires_at         TIMESTAMPTZ,
    revoked_at         TIMESTAMPTZ,
    created_by         UUID,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (resource_id, subject_kind, subject_id),
    FOREIGN KEY (tenant_id, resource_id) REFERENCES published_resources (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX entitlements_subject_idx ON entitlements (tenant_id, subject_kind, subject_id);

CREATE TABLE sessions (
    id           UUID PRIMARY KEY,
    tenant_id    UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    resource_id  UUID        NOT NULL,
    machine_id   UUID        NOT NULL,
    user_id      UUID        NOT NULL,
    gateway_id   UUID REFERENCES gateways (id) ON DELETE SET NULL,
    relay_id     UUID REFERENCES relays (id) ON DELETE SET NULL,
    state        TEXT        NOT NULL DEFAULT 'PENDING'
                     CHECK (state IN ('PENDING', 'ACTIVE', 'CLOSED', 'FAILED')),
    role         TEXT        NOT NULL,
    -- The ticket's jti, so a gateway can prove a ticket was issued for this
    -- session and refuse a second use of it.
    ticket_jti   TEXT        NOT NULL UNIQUE,
    client_ip    TEXT,
    client_os    TEXT,
    bytes_up     BIGINT      NOT NULL DEFAULT 0,
    bytes_down   BIGINT      NOT NULL DEFAULT 0,
    close_reason TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at   TIMESTAMPTZ,
    ended_at     TIMESTAMPTZ,
    FOREIGN KEY (tenant_id, resource_id) REFERENCES published_resources (tenant_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX sessions_user_idx ON sessions (tenant_id, user_id, created_at DESC);
CREATE INDEX sessions_live_idx ON sessions (tenant_id, state) WHERE state IN ('PENDING', 'ACTIVE');

CREATE TABLE refresh_tokens (
    id         UUID PRIMARY KEY,
    tenant_id  UUID        NOT NULL,
    user_id    UUID        NOT NULL,
    token_hash TEXT        NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id);

-- Ed25519 keys used to sign session tickets. Kept in the database so every
-- manager replica signs with the same key and gateways see a stable JWKS.
CREATE TABLE signing_keys (
    kid         TEXT PRIMARY KEY,
    private_key BYTEA       NOT NULL,
    public_key  BYTEA       NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    retired_at  TIMESTAMPTZ
);

CREATE TABLE audit_log (
    id             UUID PRIMARY KEY,
    tenant_id      UUID,
    actor_user_id  UUID,
    action         TEXT        NOT NULL,
    target_kind    TEXT,
    target_id      UUID,
    result         TEXT        NOT NULL CHECK (result IN ('ALLOW', 'DENY', 'ERROR')),
    detail         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    ip             TEXT,
    at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_tenant_at_idx ON audit_log (tenant_id, at DESC);
